### PR TITLE
Cask setup and auto-deploy packages

### PR DESCRIPTION
**Pull request by jgkamat**
This PR:

1. Sets up generation through cask, so anyone can build the site easily
2. Sets up autodeployment, so the site will be auto-deployed whenever we push to master.

Let me know if you spot any issues in the new site, and I'll fix them as they come up! This is pretty likely, since I rewrote the build system (this time supporting non-gui environments).

### CODE REVIEW

**Comment by jgkamat** [comment]
Oh by the way, to generate the packages yourself, you can first [install cask](https://github.com/cask/cask), then run `cask install` in the root of this repo (to set up dependencies), and then run `cask eval "(progn (require 'robocup-training) (my-org-publish))"`.

I should probably make a makefile for this so we don't need to remember these commands...

**Comment by jgkamat** [comment]
Also kind of unrelated, but we need to address the issue of 'should we keep the old slide site around for archival purposes, or should we just overwrite it on the next year' (which is totally up to you).

**Comment by joshhting** [comment]
Oh that's a good point, we could just put each year's slides into a different folder. Keeping them around would definitely be a good idea. In which case I shouldn't have overwritten 1.org :P

**Comment by jgkamat** [comment]
Once this PR is merged, I'll copy everything over to a 2016 folder and start with a blank slate, I don't want to do it on top of this branch since that would get a little messy. I'll open an issue to track it.

**Comment by joshhting** [comment]
Merge whenever you're ready :+1:

**Pull request merged**
